/**
 * Deployed contracts map (auto-generated by scripts/generate-frontend-artifacts.mjs).
 * Do not edit manually.
 */
import { trellisVaultAbi, strategyErc4626Abi } from "./abi";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
